### ISSUE TITLE
algorithm_comparisons.r execution halted

### ISSUE THREAD

**Issue by Cyber-Vadok** [FraunhoferChalmersCentre/s-raster#1] opened 2023-11-23 21:25 UTC
```
10,DBStream,23.429,23.472,115
10,DBStream,17.956,17.982,114 
10,DBStream,24.748,24.800,111 
10,DBStream,23.119,23.174,110 
Scalar=3162.277660

Use timed data
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘colnames’ is not a valid field or method name for reference class “SRaster”
Calls: system.time -> update -> update.DSC_R -> $ -> envRefInferField
Timing stopped at: 0.014 0.004 0.018
Execution halted
```

Data is generated from generator_big.py, timestamps are added via change_label.py. R script stopped working on the S-RASTER timed_datafile reading. Followed readme and not working.

**Comment by tgmgm** [comment] 2023-11-24 08:21
Is this a general issue or does it only affect DBStream? To narrow down the problem, perhaps consider commenting out DBStream and see if you can get the code to run then.

Also, there could be issues with dependencies so you may have to downgrade some libraries.

**Comment by Cyber-Vadok** [comment] 2023-11-26 11:53
```
algorithms <- list(
  # "Windowed k-means"=function() { DSC_TwoStage(micro = DSC_Window(horizon = 100), #dsc=data stream clustering
  #              macro = DSC_Kmeans(k = 100)) },
  # "DStream"=function() { DSC_DStream(gridsize = 0.0003) },
  # "DBStream"=function() { DSC_DBSTREAM(r = 0.0002, Cm=0.0, gaptime = 25000) },
  "S-RASTER"=function() { DSC_SRaster(p=3.5, window_size = 10) }
)
```

Use timed data
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘colnames’ is not a valid field or method name for reference class “SRaster”
Calls: system.time -> update -> update.DSC_R -> $ -> envRefInferField
Timing stopped at: 0.026 0 0.026
Execution halted

The problem seems to be S-Raster.

**Comment by Cyber-Vadok** [comment] 2023-11-26 13:15
as a counterproof, this worked:
```
algorithms <- list(
  "Windowed k-means"=function() { DSC_TwoStage(micro = DSC_Window(horizon = 100),
               macro = DSC_Kmeans(k = 100)) },
  "DStream"=function() { DSC_DStream(gridsize = 0.0003) },
  "DBStream"=function() { DSC_DBSTREAM(r = 0.0002, Cm=0.0, gaptime = 25000) }
  # Remove "S-RASTER" from the list of algorithms
)
```
10,DBStream,36.946,37.105,110 
Done!

**Comment by gregorulm** [comment] 2023-11-26 14:15
@SimonSmithFCC @adnilsson Could you please have a look if you still have the code installed on your workstations?

**Comment by gregorulm** [comment] 2023-11-27 19:57
I have heard back from my former colleagues. They also think the issue is due to mismatched dependencies. Maybe set up a virtual machine and use older versions of the stated dependencies, and then report back. Which versions do you currently use?

To quote from their email, "For example, R 4.0 was released in April 2020, so we may have used R 3.x, especially if we used a Ubuntu LTS VM. The R [stream package](https://www.rdocumentation.org/packages/stream/versions/2.0-0) is also in 2.0 since September 3rd, 2022."

I would also recommend starting with downgrading R and the `stream` package.

**Comment by Cyber-Vadok** [comment] 2023-11-29 16:57
I downgraded stream to 1.2-4 and Rcpp to 1.0.0, also need to install magick and animation manually. Now it's working.
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/stream/stream_1.2-4.tar.gz"; install.packages(packageurl, repos=NULL, type="source")

packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_1.0.0.tar.gz"; install.packages(packageurl, repos=NULL, type="source")
```
I think the readme needs an update. Thanks for the support.

**Comment by gregorulm** [comment] 2023-11-29 20:54
This information is helpful. Thanks for letting us know!

**Comment by gregorulm** [comment] 2023-11-29 20:58
@Cyber-Vadok I just merged your PR. If you end up using S-RASTER for a project, thesis, or paper, please reach out again as I would be curious to have a look. Thanks again for your feedback.

**Comment by gregorulm** [comment] 2023-11-29 20:58
Issue closed.

**Closed as completed by gregorulm** 2023-11-29 20:58 UTC
